### ISSUE TITLE
Configuration initiale

### ISSUE THREAD

**Issue by etienneJan1** [FelixHumeau/ECO2TRIP#1]
- [x] Configurer le dépôt Git
- [x] Initialisation du back
- [x] Initialisation du front
