### ISSUE TITLE
Recherche de logement

### ISSUE THREAD

**Issue by etienneJan1** [FelixHumeau/ECO2TRIP#14]
- [ ] Créer le modèle logement
- [ ] Intégrer une API de données de logement
- [ ] Créer la page de recherche de logement
