### ISSUE TITLE
Authentification

### ISSUE THREAD

**Issue by etienneJan1** [FelixHumeau/ECO2TRIP#5]
- [ ] Créer le modèle utilisateur
- [ ] Implémenter le middleware d'authentification
- [ ] Créer les routes d'inscription et de connexion
- [ ] Créer les pages de connexion et d'inscription
